export const ROUTER = {
  HOME_PAGE_ROUTE: "/",
  ABOUT_PAGE_ROUTE: "/about",
  CONTACTS_PAGE_ROUTE: "/contacts",
  NEWS_PAGE_ROUTE: "/news",
  NEWS_SINGLE_PAGE_ROUTE: "/news/:id",
  STATE_SUPPORT_PAGE_ROUTE: "/state_support",
  STATE_SUPPORT_PAGE_SINGLE_ROUTE: "/state_support/:id",
  EVENTS_PAGE_ROUTE: "/events",
  SERVICES_PAGE_ROUTE: "/services",
  ANTIKRIZIS_MODE_PAGE_ROUTE: "/antikrizis-mode",
  SELFEMPLOYMENT_MODE_PAGE_ROUTE: "/self-employment-mode",
  ADMIN_PAGE_ROUTE: "/admin_panel",
  ERROR_PAGE_ROUTE: "*",
};
